# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Learn Like a Machine
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on data science, machine learning, statistics, Python
  programming, R programming, and how to teach them. You may also
  find an occasional foray into cooking, music, or gaming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ohheyitsmason
github_username:  MasonGallo

# Build settings
markdown: kramdown
